on:
  push:
    branches:
    - develop
jobs:
  job1:
    runs-on: self-hosted
    steps:
      - name: Hello
        run: echo 'Hello'
        env:
          ACTIONS_RUNNER_DEBUG: ${secrets.ACTIONS_RUNNER_DEBUG}